routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
  
Route::get('profile','ProfileController@index')->name('profile');
Route::post('profile/changePassword','ProfileController@changePassword')->name('profile.changePassword');
Route::post('profile/changeName','ProfileController@updateName')->name('profile.updateName');

Route::get('contact-us-messages/unseen','ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
Route::get('contact-us-messages/reply/{id}','ContactUsMessageController@reply')->name('contact-us-messages.reply');
Route::post('contact-us-messages/reply/{id}','ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
Route::resource('contact-us-messages', 'ContactUsMessageController',['only' => ['show','destroy','index']]);
Route::get('getUnseenMsgCount','ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
Route::get('getUnseenMsg','ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

Route::resource('users', 'UserController',['except' => ['create','show']]);
Route::resource('roles', 'RoleController',['except' => ['show']]);
Route::resource('teams', 'TeamController',['except' => ['show']]);

Route::resource('/project/communications','CommunicationController',['except' => ['create']]);
Route::get('/project/listcommunications','CommunicationController@listCommunicationByProject');
Route::resource('/project/projectlogs','ProjectLogController',['except' => ['create','show']]);
Route::get('/project/listlogs','ProjectLogController@listLogsByProject');
Route::get('storage/projectfiles/{filename}', 'ProjectLogController@getFile')->name('projects.getFile');

Route::get('/projects/kanban','ProjectController@kanban')->name('projects.kanban');
Route::post('/projects/updateStatus','ProjectController@updateStatus');
Route::resource('projects', 'ProjectController',['except' => ['create','show']]);
Route::resource('/project/contactdetails','ContactDetailsController',['except' => ['create']]);

Route::get('projects/{id}/getTasks', 'ProjectController@getTasks');

Route::get('/tasks/kanban','TaskController@kanban')->name('tasks.kanban');
Route::post('/tasks/updateStatus','TaskController@updateStatus');

Route::get('storage/taskfiles/{filename}', 'TaskLogController@getFile')->name('tasks.getFile');
Route::resource('tasklogs', 'TaskLogController',['except' => ['create','show']]);
Route::get('/tasks/listlogs','TaskLogController@listLogsByTask');

Route::get('tasks/{id}/getMembers', 'TaskAssignController@getTeamMembers');
Route::resource('task/assignments', 'TaskAssignController',['except' => ['create','show','edit','update']]);

Route::get('task/verifications', 'TaskVerificationController@index')->name('verifications.index');
// Route::get('tasks/{id}/verify', 'TaskVerificationController@create')->name('verifications.create');
Route::post('task/verify', 'TaskVerificationController@store')->name('verifications.store');

Route::resource('tasks', 'TaskController',['except' => ['show']]);

Route::post('/menus/updatePriority','MenuController@updatePriority');
Route::resource('menus', 'MenuController',['except' => ['create','show']]);

Route::get('/dashboard','AdminController@index');
Route::get('/','AdminController@index');

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use SoftDeletes;
    public function state()
    {
        return $this->belongsTo('App\Status', 'status');
    }

    public function creator()
    {
        return $this->belongsTo('App\User','created_by')->withTrashed();
    }

    public function updator()
    {
        return $this->belongsTo('App\User', 'updated_by')->withTrashed();
    }

    public function teams()
    {
        return $this->belongsToMany('App\Team');
    }

    public function logs(){
        return $this->hasMany('App\ProjectLog');
    }

    public function tasks()
    {
        return $this->hasMany('App\Task');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\ProjectsDataTable;
use App\Services\ProjectService;
use App\Services\TaskService;
use App\Project;
use App\Team;
use App\Status;
use Auth;
use Illuminate\Support\Collection;

class ProjectController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view',Project::class);

        $dataTable = new ProjectsDataTable;
        $statuses = Status::where('modal','Project')->get();
        $teams = Team::get();

        return $dataTable->render('projects.index',compact('statuses','teams'));
    }

    public function getTasks($id,Request $request){
        $project = Project::findOrFail($id);

        $tasks = TaskService::tasks()->where('project_id',$project->id)->toArray();

        return response()->json(array_values($tasks), 200);
    }

    public function kanban(){
        $this->authorize('view',Project::class);

        $statuses = Status::where('modal','Project')->get();
        $projects= ProjectService::projects();
       

        // dd($projects);

        return view('projects.kanban',compact('statuses','projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create',Project::class);
        
        $request->validate([
            'name' => 'required|string|max:191',
            'description' => 'required',
            'company' => 'required|string|max:191',
            'status' => 'required|exists:statuses,id',
            'teams' => 'required|min:1',
            'teams.*' => 'required|exists:teams,id',
        ],[
            'teams.*.exists' => 'Team Assignment Failed'
        ]);

        $project = new Project;
        $project->name = $request->name;
        $project->description = $request->description;
        $project->company = $request->company;
        $project->status = $request->status;
        $project->created_by = Auth::user()->id;
        $project->updated_by = Auth::user()->id;

        $project->save();

        $project->teams()->attach($request->teams);

        $request->session()->flash('success', 'Project Added Successfully');

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update',$project = Project::findOrFail($id));
        
        
        $statuses = Status::get();
        $teams = Team::get();

        return view('projects.edit',compact('project','statuses','teams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update', $project = Project::findOrFail($id));
        
        $request->validate([
            'name' => 'required|string|max:191',
            'description' => 'required',
            'company' => 'required|string|max:191',
            'teams' => 'required|min:1',
            'teams.*' => 'required|exists:teams,id',
        ],[
            'teams.*.exists' => 'Team Assignment Failed'
        ]);

              
        $project->name = $request->name;
        $project->description = $request->description;
        $project->company = $request->company;
        $project->updated_by = Auth::user()->id;

        $project->save();

        $project->teams()->sync($request->teams);

        $request->session()->flash('success', 'Project Updated Successfully');

        return redirect()->route('projects.index');        
    }

    public function updateStatus(Request $request){
        $this->authorize('updateStatus', $project = Project::findOrFail($request->project_id));
        
        $request->validate([
            'project_id' => 'required|exists:projects,id',
            'status_id' => 'required|exists:statuses,id',
            'description' => 'required',            
        ]);

         
        $project->status = $request->status_id;
        $project->save();

        $project->logs()->create([
            'description' => $request->description,
            'status' => $request->status_id,
            'created_by' => Auth::user()->id,
        ]);

        return response()->json('status updated', 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $this->authorize('destroy',$project = Project::findOrFail($id));
        
        
        $project->delete();
        
        $request->session()->flash('success', 'Project Deleted Successfully');

        return redirect()->back();
    }
}

resources/views/projects/action.blade.php
{{-- <a class="btn btn-outline-info btn-sm" title="View" href="{{ route('projects.show',$project->id) }}"><i class="icon-eye"></i></a> --}}
@can('update',$project)
    <a class="btn btn-outline-warning btn-sm" title="Edit" href="{{ route('projects.edit',$project->id) }}"><i class="icon-edit"></i></a>
@endcan
@can('viewcommunications',$project)
<a class="btn btn-outline-warning btn-sm" title="Edit" href="/project/listcommunications/?id={{$project->id}}"><i class="icon-android-chat"></i></a>
@endcan
@can('viewlog',$project)
<a class="btn btn-outline-warning btn-sm" title="Edit" href="/project/listlogs/?id={{$project->id}}"><i class="icon-drag"></i></a>
@endcan
{{-- @endcan  --}}
@can('destroy',$project)
    <form action="{{ route('projects.destroy',$project->id) }}" method="POST" style="display:inline">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE" >

        <button title="delete" type="button" class="btn btn-outline-danger btn-sm deleteButton"><i class="icon-trash-o"></i></button>
    </form>
@endcan

resources/views/projects/edit.blade.php
@extends('layouts.admin')

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
@endsection

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Edit Project</h2>
        </div>
        <div class="text-xs-right">
            <a href="{{ route('projects.index') }}" class="btn btn-primary btn-min-width mr-2 mb-1">Back</a>
        </div>
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('projects.update',$project->id) }}">
                        {{ csrf_field() }}
                        <input name="_method" value="PATCH" hidden />
                        
                        <div class="form-body">
                            <h4 class="form-section"><i class="icon-eye6"></i> About Project</h4>

                            <div class="form-group">
                                <label for="name">Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" placeholder="Name" class="form-control" name="name" value="{{ $project->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control{{ $errors->has('description') ? ' border-danger' : '' }}" placeholder="Description"  name="description" required>{{ $project->description }}</textarea>

                                @if ($errors->has('description'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <div class="input-group">   
                                    <label for="company">Company</label>
                                    <input type="text" class="form-control{{ $errors->has('company') ? ' border-danger' : '' }}" id="company" name="company" value="{{ $project->company }}" placeholder="Company" required>
                                </div>
                                @if ($errors->has('company'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('company') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <?php $oldValue = $project->teams->pluck('id')->toArray() ? : [] ?>
                            <div class="form-group">
                                <div class="input-group">  
                                    <label for="teamsSelect">Teams</label><br>
                                    <select class="form-control{{ $errors->has('password') ? ' border-danger' : '' }} js-example-basic-multiple" id="teamsSelect" name="teams[]" multiple="multiple" style="width:100%" required>
                                        @foreach($teams as $team)
                                            <option value="{{ $team->id }}" {{ in_array($team->id,$oldValue) ? 'selected' : '' }}>{{ $team->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('teams'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('teams') }}</strong>
                                    </div>
                                @endif

                                @if ($errors->has('teams.*'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('teams.*') }}</strong>
                                    </div>
                                @endif
                                
                            </div>

                         
                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-success">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#teamsSelect').select2({
                'placeholder': 'Select Teams'
            });
        });

    </script>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.admin')

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
@endsection

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Projects</h2>
        </div>
        
            <div class="text-xs-right">
                <a href="{{ route('projects.kanban') }}" class="btn btn-primary btn-min-width mr-2 mb-1">Switch to Kanban View</a>
            </div>

    </div>
    <div class="content-body">
        @can('create', App\Project::class)
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><a data-action="collapse">Add New Project</a></h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse {{ count($errors)>0 ? 'in':'out' }}">
                    <div class="card-block card-dashboard">
                        <form class="form" method="POST" id="AddProjectForm" action="{{ route('projects.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="form-body">
                                <h4 class="form-section"><i class="icon-eye6"></i> About Project</h4>
    
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" placeholder="Name" class="form-control" name="name" value="{{ old('name') }}" required>
    
                                    @if ($errors->has('name'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
    
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea rows="5" class="form-control{{ $errors->has('description') ? ' border-danger' : '' }}" placeholder="Description"  name="description" required>{{ old('description') }}</textarea>
    
                                    @if ($errors->has('description'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </div>
                                    @endif
                                </div>
    
                                <div class="form-group">
                                    <div class="input-group">   
                                        <label for="company">Company</label>
                                        <input type="text" class="form-control{{ $errors->has('company') ? ' border-danger' : '' }}" id="company" name="company" value="{{ old('company') }}" placeholder="Company" required>
                                    </div>
                                    @if ($errors->has('company'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('company') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <?php $oldValue = old('teams') ? : [] ?>
                                <div class="form-group">
                                    <div class="input-group">  
                                        <label for="teamsSelect">Teams</label><br>
                                        <select class="form-control{{ $errors->has('password') ? ' border-danger' : '' }} js-example-basic-multiple" id="teamsSelect" name="teams[]" multiple="multiple" style="width:100%" required>
                                            @foreach($teams as $team)
                                                <option value="{{ $team->id }}" {{ in_array($team->id,$oldValue) ? 'selected' : '' }}>{{ $team->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('teams'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('teams') }}</strong>
                                        </div>
                                    @endif

                                    @if ($errors->has('teams.*'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('teams.*') }}</strong>
                                        </div>
                                    @endif
                                    
                                </div>

                                <div class="form-group">
                                    <div class="input-group">  
                                        <label for="status">Status</label><br>
                                        <select class="form-control{{ $errors->has('status') ? ' border-danger' : '' }} js-example-basic-multiple" id="status" name="status" required>
                                            <option value="" selected disabled>Choose a Status</option>
                                            @foreach($statuses as $status)
                                                <option value="{{ $status->id }}">{{ $status->status }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('status'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('status') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
    
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        @endcan
        
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard dataTable">

                    {!! $dataTable->table()  !!}
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#teamsSelect').select2({
                'placeholder': 'Select Teams'
            });
        });
    </script>

    {!! $dataTable->scripts() !!}
@endsection