routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
  
Route::get('profile','ProfileController@index')->name('profile');
Route::post('profile/changePassword','ProfileController@changePassword')->name('profile.changePassword');
Route::post('profile/changeName','ProfileController@updateName')->name('profile.updateName');

Route::get('contact-us-messages/unseen','ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
Route::get('contact-us-messages/reply/{id}','ContactUsMessageController@reply')->name('contact-us-messages.reply');
Route::post('contact-us-messages/reply/{id}','ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
Route::resource('contact-us-messages', 'ContactUsMessageController',['only' => ['show','destroy','index']]);
Route::get('getUnseenMsgCount','ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
Route::get('getUnseenMsg','ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

Route::resource('users', 'UserController',['except' => ['create','show']]);
Route::resource('roles', 'RoleController',['except' => ['show']]);
Route::resource('teams', 'TeamController',['except' => ['show']]);

Route::resource('/project/communications','CommunicationController',['except' => ['create']]);
Route::get('/project/listcommunications','CommunicationController@listCommunicationByProject');
Route::resource('/project/projectlogs','ProjectLogController',['except' => ['create','show']]);
Route::get('/project/listlogs','ProjectLogController@listLogsByProject');
Route::get('storage/projectfiles/{filename}', 'ProjectLogController@getFile')->name('projects.getFile');

Route::get('/projects/kanban','ProjectController@kanban')->name('projects.kanban');
Route::post('/projects/updateStatus','ProjectController@updateStatus');
Route::resource('projects', 'ProjectController',['except' => ['create','show']]);
Route::resource('/project/contactdetails','ContactDetailsController',['except' => ['create']]);

Route::get('projects/{id}/getTasks', 'ProjectController@getTasks');

Route::get('/tasks/kanban','TaskController@kanban')->name('tasks.kanban');
Route::post('/tasks/updateStatus','TaskController@updateStatus');

Route::get('storage/taskfiles/{filename}', 'TaskLogController@getFile')->name('tasks.getFile');
Route::resource('tasklogs', 'TaskLogController',['except' => ['create','show']]);
Route::get('/tasks/listlogs','TaskLogController@listLogsByTask');

Route::get('tasks/{id}/getMembers', 'TaskAssignController@getTeamMembers');
Route::resource('task/assignments', 'TaskAssignController',['except' => ['create','show','edit','update']]);

Route::get('task/verifications', 'TaskVerificationController@index')->name('verifications.index');
// Route::get('tasks/{id}/verify', 'TaskVerificationController@create')->name('verifications.create');
Route::post('task/verify', 'TaskVerificationController@store')->name('verifications.store');

Route::resource('tasks', 'TaskController',['except' => ['show']]);

Route::post('/menus/updatePriority','MenuController@updatePriority');
Route::resource('menus', 'MenuController',['except' => ['create','show']]);

Route::get('/dashboard','AdminController@index');
Route::get('/','AdminController@index');

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;
    use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function teams()
    {
        return $this->belongsToMany('App\Team')->withPivot('role_id');
    }

    public function teamrole($team_id)
    {
        $role_id= TeamUser::where('user_id',$this->id)->where('team_id',$team_id);
        return Role::findOrFail($role_id);
    }
    public function teamroles($project_id)
    {
        $team_ids=Project::findOrFail($project_id)->teams->pluck('id');
        $role_ids=TeamUser::where('user_id',$this->id)->whereIn('team_id',$team_ids)->get()->pluck('role_id');
        return Role::whereIn('id',$role_ids)->get();
    }

    public function mytasks()
    {
        return $this->belongsToMany('App\Task', 'task_assigns', 'assigned_to', 'task_id');
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\UsersDataTable;
use App\User;
use App\Role;
use App\Mail\NewUserAdded;
use Mail;

class UserController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth');
        // $this->authorizeResource(User::class, 'user');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view',User::class);

        $dataTable = new UsersDataTable;
        $roles = Role::get();

        return $dataTable->render('users.index',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create',User::class);
        
        $request->validate([
            'name' => 'required|string|max:191',
            'email' => 'required|string|email|max:191|unique:users',
            'password' => 'required|string|min:6',
            'roles' => 'required|min:1',
            'roles.*' => 'required|exists:roles,id',
        ],[
            'roles.*.exists' => 'Role Assignment Failed'
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);

        $user->assignRole($request->roles);

        $user->save();

        Mail::to($user->email)->send(new NewUserAdded($user,$request->password));

        $request->session()->flash('success', 'User Added Successfully');

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update',User::class);
        
        $user = User::findOrFail($id);
        $roles = Role::get();

        return view('users.edit',compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update',User::class);
        
        $user = User::findOrFail($id);

        if($request->input('email') == $user->email){
            $request->validate([
                'name' => 'required|string|max:191',
                'password' => 'nullable|string|min:6',
                'status' => 'required|string|in:Active,Inactive',
                'roles' => 'required|min:1',
                'roles.*' => 'required|exists:roles,id',
            ],[
                'roles.*.exists' => 'Role Assignment Failed'
            ]);
        }
        else{
            $request->validate([
                'name' => 'required|string|max:191',
                'email' => 'required|string|email|max:191|unique:users',
                'password' => 'nullable|string|min:6',
                'status' => 'required|string|in:Active,Inactive',
                'roles' => 'required|min:1',
                'roles.*' => 'required|exists:roles,id',
            ],[
                'roles.*.exists' => 'Role Assignment Failed'
            ]);
        }

        $user->name = $request->name;
        $user->email = $request->email;
        $user->status = $request->status;

        $user->syncRoles($request->roles);

        if($request->password){
            $user->password = bcrypt($request->password);
            // Mail::to($user->email)->send(new UserUpdated($user,$request->password));
        }
        
        $user->save();

        $request->session()->flash('success', 'User Updated Successfully');

        return redirect()->route('users.index');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $this->authorize('destroy',User::class);
        
        $user = User::findOrFail($id);
        $user->delete();
        
        $request->session()->flash('success', 'User Deleted Successfully');

        return redirect()->back();
    }
}

resources/views/users/edit.blade.php
@extends('layouts.admin')

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
@endsection

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Edit User</h2>
        </div>
        <div class="text-xs-right">
            <a href="{{ route('users.index') }}" class="btn btn-primary btn-min-width mr-2 mb-1">Back</a>
        </div>
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('users.update',$user->id) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input name="_method" value="PATCH" hidden />
                        <div class="form-body">
                            <h4 class="form-section"><i class="icon-eye6"></i> About User</h4>

                            <div class="form-group">
                                <label for="name">Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" placeholder="Name" class="form-control" name="name" value="{{ $user->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="userinput5">Email</label>
                                <input class="form-control{{ $errors->has('email') ? ' border-danger' : '' }}" type="email" placeholder="Email"  name="email" value="{{ $user->email }}" required>

                                @if ($errors->has('email'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <div class="input-group">   
                                    <label for="password">Password (Optional)</label>
                                    <input type="text" class="form-control{{ $errors->has('password') ? ' border-danger' : '' }}" id="password" name="password" placeholder="Password" rel="gp" data-size="10" data-character-set="a-z,A-Z,0-9">
                                    <span class="input-group-btn"><button type="button" class="btn btn-primary getNewPass" style="margin-top:27px" title="Generate Password"><span class="icon-reload"></span></button></span>
                                </div>
                                @if ($errors->has('password'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <?php $oldValue = $user->roles->pluck('id')->toArray() ? : [] ?>
                            <div class="form-group">
                                <div class="input-group">  
                                    <label for="rolesSelect">Roles</label><br>
                                    <select class="form-control{{ $errors->has('roles') ? ' border-danger' : '' }} js-example-basic-multiple" id="rolesSelect" name="roles[]" multiple="multiple" style="width:100%" required>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" {{ in_array($role->id,$oldValue) ? 'selected' : '' }}>{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('roles'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('roles') }}</strong>
                                    </div>
                                @endif

                                @if ($errors->has('roles.*'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('roles.*') }}</strong>
                                    </div>
                                @endif
                                
                            </div>

                            <div class="form-group">
                                <div class="input-group">  
                                    <label for="status">Status</label><br>
                                    <select class="form-control{{ $errors->has('status') ? ' border-danger' : '' }} js-example-basic-multiple" id="status" name="status" required>
                                        <option value="Active" {{ $user->status == 'Active' ? 'selected' : '' }}>Active</option>
                                        <option value="Inactive" {{ $user->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                                    </select>
                                </div>
                                @if ($errors->has('status'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-success">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#rolesSelect').select2({
                'placeholder': 'Select Roles'
            });
        });
        // Generate a password string
            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');  
                var possible = '';
                if($.inArray('a-z', dataSet) >= 0){
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if($.inArray('A-Z', dataSet) >= 0){
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if($.inArray('0-9', dataSet) >= 0){
                    possible += '0123456789';
                }
                if($.inArray('#', dataSet) >= 0){
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for(var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                field.val(randString(field));
            });

    </script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin')

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
@endsection

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Users</h2>
        </div>
    </div>
    <div class="content-body">
        @can('create', User::class)
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><a data-action="collapse">Add New User</a></h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse {{ count($errors)>0 ? 'in':'out' }}">
                    <div class="card-block card-dashboard">
                        <form class="form" method="POST" id="AddUserForm" action="{{ route('users.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="form-body">
                                <h4 class="form-section"><i class="icon-eye6"></i> About User</h4>
    
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" placeholder="Name" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
    
                                    @if ($errors->has('name'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
    
                                <div class="form-group">
                                    <label for="userinput5">Email</label>
                                    <input class="form-control{{ $errors->has('email') ? ' border-danger' : '' }}" type="email" placeholder="Email"  name="email" value="{{ old('email') }}" required>
    
                                    @if ($errors->has('email'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </div>
                                    @endif
                                </div>
    
                                <div class="form-group">
                                    <div class="input-group">   
                                        <label for="password">Password</label>
                                        <input type="text" class="form-control{{ $errors->has('password') ? ' border-danger' : '' }}" id="password" name="password" value="{{ old('password') }}" placeholder="Password" rel="gp" data-size="10" data-character-set="a-z,A-Z,0-9" required>
                                        <span class="input-group-btn"><button type="button" class="btn btn-primary getNewPass" style="margin-top:27px" title="Generate Password"><span class="icon-reload"></span></button></span>
                                    </div>
                                    @if ($errors->has('password'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <?php $oldValue = old('roles') ? : [] ?>
                                <div class="form-group">
                                    <div class="input-group">  
                                        <label for="rolesSelect">Roles</label><br>
                                        <select class="form-control{{ $errors->has('password') ? ' border-danger' : '' }} js-example-basic-multiple" id="rolesSelect" name="roles[]" multiple="multiple" style="width:100%" required>
                                            @foreach($roles as $role)
                                                <option value="{{ $role->id }}" {{ in_array($role->id,$oldValue) ? 'selected' : '' }}>{{ $role->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('roles'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('roles') }}</strong>
                                        </div>
                                    @endif

                                    @if ($errors->has('roles.*'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('roles.*') }}</strong>
                                        </div>
                                    @endif
                                    
                                </div>
                            </div>
    
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        @endcan
        
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard dataTable">

                    {!! $dataTable->table()  !!}
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#rolesSelect').select2({
                'placeholder': 'Select Roles'
            });
        });
        // Generate a password string
            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');  
                var possible = '';
                if($.inArray('a-z', dataSet) >= 0){
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if($.inArray('A-Z', dataSet) >= 0){
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if($.inArray('0-9', dataSet) >= 0){
                    possible += '0123456789';
                }
                if($.inArray('#', dataSet) >= 0){
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for(var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                field.val(randString(field));
            });

    </script>

    {!! $dataTable->scripts() !!}
@endsection

resources/views/users/users-action.blade.php
{{-- <a class="btn btn-outline-info btn-sm" title="View" href="{{ route('users.show',$user->id) }}"><i class="icon-eye"></i></a> --}}
@can('update',App\User::class)
    <a class="btn btn-outline-warning btn-sm" title="Edit" href="{{ route('users.edit',$user->id) }}"><i class="icon-edit"></i></a>
@endcan

@can('destroy',App\User::class)
    <form action="{{ route('users.destroy',$user->id) }}" method="POST" style="display:inline">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE" >

        <button title="delete" type="button" class="btn btn-outline-danger btn-sm deleteButton"><i class="icon-trash-o"></i></button>
    </form>
@endcan