routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
  
Route::get('profile','ProfileController@index')->name('profile');
Route::post('profile/changePassword','ProfileController@changePassword')->name('profile.changePassword');
Route::post('profile/changeName','ProfileController@updateName')->name('profile.updateName');

Route::get('contact-us-messages/unseen','ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
Route::get('contact-us-messages/reply/{id}','ContactUsMessageController@reply')->name('contact-us-messages.reply');
Route::post('contact-us-messages/reply/{id}','ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
Route::resource('contact-us-messages', 'ContactUsMessageController',['only' => ['show','destroy','index']]);
Route::get('getUnseenMsgCount','ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
Route::get('getUnseenMsg','ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

Route::resource('users', 'UserController',['except' => ['create','show']]);
Route::resource('roles', 'RoleController',['except' => ['show']]);
Route::resource('teams', 'TeamController',['except' => ['show']]);

Route::resource('/project/communications','CommunicationController',['except' => ['create']]);
Route::get('/project/listcommunications','CommunicationController@listCommunicationByProject');
Route::resource('/project/projectlogs','ProjectLogController',['except' => ['create','show']]);
Route::get('/project/listlogs','ProjectLogController@listLogsByProject');
Route::get('storage/projectfiles/{filename}', 'ProjectLogController@getFile')->name('projects.getFile');

Route::get('/projects/kanban','ProjectController@kanban')->name('projects.kanban');
Route::post('/projects/updateStatus','ProjectController@updateStatus');
Route::resource('projects', 'ProjectController',['except' => ['create','show']]);
Route::resource('/project/contactdetails','ContactDetailsController',['except' => ['create']]);

Route::get('projects/{id}/getTasks', 'ProjectController@getTasks');

Route::get('/tasks/kanban','TaskController@kanban')->name('tasks.kanban');
Route::post('/tasks/updateStatus','TaskController@updateStatus');

Route::get('storage/taskfiles/{filename}', 'TaskLogController@getFile')->name('tasks.getFile');
Route::resource('tasklogs', 'TaskLogController',['except' => ['create','show']]);
Route::get('/tasks/listlogs','TaskLogController@listLogsByTask');

Route::get('tasks/{id}/getMembers', 'TaskAssignController@getTeamMembers');
Route::resource('task/assignments', 'TaskAssignController',['except' => ['create','show','edit','update']]);

Route::get('task/verifications', 'TaskVerificationController@index')->name('verifications.index');
// Route::get('tasks/{id}/verify', 'TaskVerificationController@create')->name('verifications.create');
Route::post('task/verify', 'TaskVerificationController@store')->name('verifications.store');

Route::resource('tasks', 'TaskController',['except' => ['show']]);

Route::post('/menus/updatePriority','MenuController@updatePriority');
Route::resource('menus', 'MenuController',['except' => ['create','show']]);

Route::get('/dashboard','AdminController@index');
Route::get('/','AdminController@index');

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

app/Http/Controllers/CommunicationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Services\ProjectService;
use App\Services\ProjectCommunicationService;
use App\ProjectCommunication;
use App\ContactDetail;
use Auth;

class CommunicationController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $this->authorize('view',ProjectCommunication::class);
        $projects=ProjectService::projects();
        $communications = ProjectCommunicationService::projectcommunications();
        $contactdetails=ContactDetail::get();
        // dd($communications);
        return view('communications.index',compact('communications','projects','contactdetails'));

    }

    public function  listCommunicationByProject(Request $request)
    {
        $for_project=Project::findOrFail($request->id);

         $this->authorize('viewcommunications',$for_project);
        $projects=Project::get();
        $communications = ProjectCommunication::where('project_id',$request->id)->orderBy('created_at','desc')->paginate(10);
        $contactdetails=ContactDetail::get();

        return view('communications.index',compact('communications','for_project','projects','contactdetails'));

    }

    public function store(Request $request)
    {
        $project=Project::findOrFail($request->project);
        $this->authorize('create_project_communications',$project);

        $request->validate([
            'description' => 'required',
            'project' => 'required|min:1',
            'contactdetail'=>'required|min:1',
            'contactdetail.*' => 'required|exists:contactdetails,id',
        ],[
            'project.*.exists' => 'Project Assignment Failed',
            'contactdetail.*.exists' => 'Contact Details Assignment Failed'

        ]);

        $com= new ProjectCommunication;
        $com->description=$request->description;
        $com->project_id=$request->project;
        $com->contactdetail_id=$request->contactdetail;
        $com->created_by = Auth::user()->id;
        $com->updated_by=Auth::user()->id;
        $com->save();

        $request->session()->flash('success', 'Communication log Added Successfully');

        return redirect()->back();

        
    }

    public function edit($id)
    {

        $communication=ProjectCommunication::findOrFail($id);
        $this->authorize('update',$communication);

        return view('communications.edit',compact('communication'));
    }

    public function update(Request $request,$id)
    {
        $com= ProjectCommunication::findOrFail($id);

        $request->validate([
            'description' => 'required',
           
        ]

        );
        $this->authorize('update',$com);
        
        $com->description=$request->description;
        $com->updated_by=Auth::user()->id;
        $com->save();

        $request->session()->flash('success', 'Communication log Edited Successfully');

        return redirect()->to(route('communications.index'));   
    }
}

resources/views/communications/edit.blade.php
@extends('layouts.admin')



@section('body')

<div class="card">
        <div class="card-header">
            <h4 class="card-title"><a data-action="collapse">Edit Communication Log</a></h4>
            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
            <div class="heading-elements">
                <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="card-body {{ count($errors)>0 ? 'in':'out' }}">
            <div class="card-block card-dashboard">
                <form class="form" method="POST" id="AddContactdetailForm" action="{{ route('communications.update',$communication->id) }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <input type="text" name="_method" value="PUT" hidden/>
                    <div class="form-body">

                        <div class="form-group">
                            <label for="name">Communication Text</label>
                        <textarea class="form-control{{ $errors->has('description') ? ' border-danger' : '' }}" id="description" type="text" placeholder="Description" class="form-control" name="description" value="{{ old('description') }}" required>{{$communication->description}}</textarea>
                            @if ($errors->has('description'))
                                <div class="alert alert-danger no-border mb-2">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </div>
                            @endif
                        </div>

                    </div>

                    <div class="form-actions right">
                        <button type="submit" class="btn btn-primary">
                            <i class="icon-check2"></i> Save
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/communications/index.blade.php
@extends('layouts.admin')



@section('body')
    @can('create', App\ProjectCommunication::class)
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a data-action="collapse">Add New Communication Log</a></h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse {{ count($errors)>0 ? 'in':'out' }}">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" id="AddContactdetailForm" action="{{ route('communications.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-body">

                            <div class="form-group">
                                <label for="name">Communication</label>
                                <textarea class="form-control{{ $errors->has('description') ? ' border-danger' : '' }}" id="description" type="text" placeholder="Description" class="form-control" name="description" value="{{ old('description') }}" required></textarea>
                                @if ($errors->has('description'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </div>
                                @endif
                            </div>

                            
                            <?php $oldValue = old('projects') ? : [] ?>
                            <div class="form-group">
                                <div class="input-group">  
                                    <label for="projectsSelect">Project</label><br>
                                    <select class="form-control{{ $errors->has('projects') ? ' border-danger' : '' }}" id="" name="project" style="width:100%" required>
                                        @foreach($projects as $project)
                                            <option value="{{ $project->id }}" {{!in_array($project->id,$oldValue) && isset($for_project) && $project->id==$for_project->id ? 'selected': ''}} {{ in_array($project->id,$oldValue) ? 'selected' : '' }}>{{ $project->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('projects'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('projects') }}</strong>
                                    </div>
                                @endif

                                @if ($errors->has('projects.*'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('projects.*') }}</strong>
                                    </div>
                                @endif
                                
                            </div>
                            <?php $oldValue = old('projects') ? : [] ?>
                            <div class="form-group">
                                <div class="input-group">  
                                    <label for="projectsSelect">Contact Details</label><br>
                                    <select class="form-control{{ $errors->has('contactdetails') ? ' border-danger' : '' }}" id="" name="contactdetail" style="width:100%" required>
                                        @foreach($contactdetails as $contactdetail)
                                            <option value="{{ $contactdetail->id }}" {{ in_array($contactdetail->id,$oldValue) ? 'selected' : '' }}>{{ $contactdetail->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if ($errors->has('contactdetails'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('contactdetails') }}</strong>
                                    </div>
                                @endif

                                @if ($errors->has('contactdetails.*'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('contactdetails.*') }}</strong>
                                    </div>
                                @endif
                                
                            </div>

                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcan
  

    <div class="card" style="">
        <div class="card-body">

            <div class="card-block">
                <h4 class="card-title">Communication logs  {{isset($for_project)?' for '.$for_project->name:''}}</h4>
             </div>

             <div class="media-list">
                @foreach($communications as $com)

                <div class="media">
                    <a class="media-left" href="#">
                        <i style="font-size: 44px;" class="fa fa-comment-o"></i>
                    </a>
                    <div class="media-body">
                        <div class="row">
                            <div class="col-md-8">
                                    <p class="media-heading" style="font-size:20px">Contact Person: <a href="{{ route('contactdetails.show',$com->contactDetail->id) }}">{{$com->contactDetail->name}}</a></p>
                                    <p class="media-heading" style="font-size:20px">Message: </p>
                                   <p style="text-align:justify; font-size:17px" > {{$com->description}}</p>
                                   @can('update',$com)
                                        <a class="btn btn-outline-warning btn-sm" title="Edit" href="{{ route('communications.edit',$com->id) }}"><i class="icon-edit"></i></a>
                                    @endcan
                               <br>
                            </div>
                            <div class="col-md-4">
                                   
                        <p class="">
                                Project: {{$com->project->name}}<br> 
                                Created By: {{$com->creator->name}}<br>
                                Created On: {{ date('M j, Y', strtotime($com->created_at)) }}<br>
                            </p>
                            </div>
                        </div>
                     
                    </div>
                </div>
                @endforeach
            </div>
           
            <div class="text-xs-center mb-3">
                    <nav aria-label="Page navigation">
                        {{ $communications->links('partials.pagination') }}
                    </nav>
                </div>
        </div>
    </div>
@endsection